### PR TITLE
Fixes issue #8 Styled 'credits' item in footer

### PR DESCRIPTION
**Pull request by KukkadapuSushma**
The "Credits" item in footer is styled : 

Updated look :+1: 

image

### CODE REVIEW

**Comment by KukkadapuSushma** [comment]
@yochannah 

Current 'Credits' : 

image


Updated 'Credits' item in footer : 

image

**Comment by yochannah** [comment]
@KukkadapuSushma Thanks for the PR! A couple of things need to be addressed before this can be merged: 

1. This is a small one - could we make the background of the link transparent rather than white? Right now it really leaps out to your eye more than any other link in the footer.
2. This is a slightly bigger issue: I think your hugo is still generating things slightly strangely. See the "files changed" section of this PR - a lot of the content is strange or has gone missing. Also shown in the screenshot below.

image

Maybe try just committing the partial file you've changed (and possibly the css / less file if you need to make any style changes) but don't include the docs file? Once 1 and 2 are fixed with can probably merge :) :+1: 

Other than that, good job!

**Comment by KukkadapuSushma** [comment]
@yochannah Sure!! Will update!

**Comment by KukkadapuSushma** [comment]
@yochannah 
Kindly review the updated PR :)

**Comment by yochannah** [comment]
Thansk for this! :+1:

**Pull request merged**
