### PR TITLE
Link-out icon functional

### PR DESCRIPTION
**Pull request by Chigael**
I made links with link-out icon open in new windows

### CODE REVIEW

**Comment by Chigael** [comment]
@yochannah Please have a look at this   Thanks

**Comment by yochannah** [comment]
hey @Chigael - thanks for making this pull request! I don't think we want _all_ of our links to open in new windows, though. There might be scenarios where we should take the icon off rather than make the links open in new windows. Do you have any thoughts which should be which?

Another minor note - there's an edit in the CSS file which is just a new line. It's nothing big, but always best to try to avoid checking in empty edits in git when possible :) no need to fix it this time.

**Comment by Chigael** [comment]
@yochannah thanks for the comment- 
I think since the link icon is not distracting the visualisation of the page it is best to make the links open in new windows.
 Also users might want to access these pages in a new window with ease and i think the link-out icon serves that purpose  

Thanks i will do better next time and avioid checking in empty edits

**Comment by yochannah** [comment]
@Chigael web usability practice considers opening links in new windows to be a bit tricky - try having a read through this :) https://www.webcredible.com/blog/beware-opening-links-new-window/ and also looking at the link from Nielsen in that article

**Comment by Chigael** [comment]
@yochannah I have gone through the links, it was really helpful
seeing as the links in the homepage is not a large image, document such as PDF or a printable version of an article its best to take off the icons from the page

**Comment by Chigael** [comment]
@yochannah shall i proceed to take off the link-out icon

**Comment by Chigael** [comment]
@yochannah Hope you are doing fine, I have modified and made changes to the link-out icon by taking it off so that it does not have to open in new window. Please review. Thank you

**Comment by uosl** [comment]
I'm sorry that we didn't follow up with your PR! It will be difficult for us to pick this up again as it's been a while since, so I'll have to close it.

**Pull request closed without merging**
