### PR TITLE
ui changes

### PR DESCRIPTION
**Pull request by tinycosmos**
#37 done

https://tinycosmos.github.io/intermine-homepage-2017/

### CODE REVIEW

**Comment by tinycosmos** [comment]
> Thanks for making this PR, @tinycosmos ! A few comments:
> 
> 1. could you please add a screenshot and summarise your changes? We have a lot of whitespace change here so it's a little tricky to spot what code you tweaked.
> 2. I can see that the style.css file has changed - this is partly my fault for insufficiently documenting this, but the style.css file shouldn't be editing directly. See https://github.com/intermine/intermine-homepage-2017/blob/master/static/style.less
> 
> Let me know when you've tweaked these aspects and I'll take another look! ✨

Screenshot (78)
line 1-3

Screenshot (79)
line 38, line 54
extra spaces must my editor's work, sorry for that.
so i have to do the same changes to style.less and style.css not to be edited at all?

**Comment by yochannah** [comment]
Sorry to be unclear 😅  @tinycosmos I meant screenshots of what the UI would look like after the changes - but the screenshots you've added here are helpful too!

**Comment by tinycosmos** [comment]
Frame 1

extra block is removed which removes the unrequired extra space 
also made the underlined colors same to maintain consistency

**Comment by yochannah** [comment]
@tinycosmos ahhhhhh, the screemshots have finally made me figure out what was going on! See https://github.com/intermine/intermine-homepage-2017/issues/37#issuecomment-605983339 - I'm going to close this PR for now but please count it as a contribution. You helped us discover a bug I didn't realise was there.

**Pull request closed without merging**
